# Configurações do Keycloak para TESTES
server.port=8081

keycloak.auth-server-url=http://localhost:8080
keycloak.realm=master
keycloak.client=admin-cli
keycloak.username=admin
keycloak.password=admin
keycloak.public-client=true

keycloak.target-realm=dev
keycloak.user-client=acme
keycloak.user-client-secret=CSrL4mm4sNfL7xtziF7BGJatzHYceyiY

kc.base-url=http://localhost:8080
kc.redirect-uris=http://localhost:3000/callback,http://localhost:4200/callback
kc.adm-user=admin
kc.adm-pass=admin

logging.level.root=INFO
logging.level.br.jus.tjpa.jsecurity=DEBUG
logging.level.org.keycloak=INFO
