# Configurações do Keycloak para TESTES
server.port=8081

keycloak.auth-server-url=http://localhost:8082
keycloak.realm=master
keycloak.username=admin
keycloak.password=admin
keycloak.client=admin-cli
keycloak.user-client-secret=eRaptSnyP0k0FLltwuCn1DIyIzRIIJIX
keycloak.target-realm=dev
keycloak.public-client=true
keycloak.client-scope-name=ciprej-app
keycloak.user-client=ciprej-app

kc.base-url=http://localhost:8082
kc.realm=${keycloak.target-realm}
kc.secret=eRaptSnyP0k0FLltwuCn1DIyIzRIIJIX
kc.client-id=ciprej-app
kc.redirect-uris=http://localhost:3000/callback,http://localhost:4200/callback
kc.adm-user=${keycloak.username}
kc.adm-pass=${keycloak.password}
kc.auto-extract-attributes=true

logging.level.root=INFO
logging.level.br.jus.tjpa.jsecurity=DEBUG
logging.level.org.keycloak=INFO
