# Configurações do Keycloak para TESTES
server.port=8081

keycloak.auth-server-url=http://localhost:8080
keycloak.realm=master
keycloak.username=admin
keycloak.password=admin
keycloak.client=admin-cli
keycloak.user-client-secret=MWWet2GSxRBVVPaFyTxufEezHTptorKd
keycloak.target-realm=dev
keycloak.public-client=true
keycloak.client-scope-name=acme

keycloak.user-client=acme

kc.base-url=http://localhost:8080
kc.realm=${keycloak.target-realm}
kc.secret=MWWet2GSxRBVVPaFyTxufEezHTptorKd
kc.client-id=acme
kc.redirect-uris=http://localhost:3000/callback,http://localhost:4200/callback
kc.adm-user=${keycloak.username}
kc.adm-pass=${keycloak.password}
kc.auto-extract-attributes=true

logging.level.root=INFO
logging.level.br.jus.tjpa.jsecurity=DEBUG
logging.level.org.keycloak=INFO
